name: Accessibility Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 11
    - name: npm install
      run: npm install
    - name: npm run build
      run: npm run build
    - name: npm run test
      run: npm run test
